ironchests_itemsanity = [
    "Gold Barrel (Itemsanity) (Iron Chests: Restocked)",
    "Diamond Chest (Itemsanity) (Iron Chests: Restocked)",
    "Iron Chest (Itemsanity) (Iron Chests: Restocked)",
    "Gold Chest (Itemsanity) (Iron Chests: Restocked)",
    "Crystal Chest (Itemsanity) (Iron Chests: Restocked)",
    "Diamond Barrel (Itemsanity) (Iron Chests: Restocked)",
    "Copper Chest (Itemsanity) (Iron Chests: Restocked)",
    "Obsidian Chest (Itemsanity) (Iron Chests: Restocked)",
    "Copper Barrel (Itemsanity) (Iron Chests: Restocked)",
    "Crystal Barrel (Itemsanity) (Iron Chests: Restocked)",
    "Obsidian Barrel (Itemsanity) (Iron Chests: Restocked)",
    "Netherite Chest (Itemsanity) (Iron Chests: Restocked)",
    "Netherite Barrel (Itemsanity) (Iron Chests: Restocked)",
    "Iron Barrel (Itemsanity) (Iron Chests: Restocked)",
    "Iron Dolly (Itemsanity) (Iron Chests: Restocked)",
    "Diamond Dolly (Itemsanity) (Iron Chests: Restocked)",
    "Blank Chest Upgrade (Itemsanity) (Iron Chests: Restocked)",
    "Key (Itemsanity) (Iron Chests: Restocked)",
    "Key Ring (Itemsanity) (Iron Chests: Restocked)",
    "Lock (Itemsanity) (Iron Chests: Restocked)",
    "Diamond Chest Upgrade (Itemsanity) (Iron Chests: Restocked)",
    "Copper Chest Upgrade (Itemsanity) (Iron Chests: Restocked)",
    "Obsidian Chest Upgrade (Itemsanity) (Iron Chests: Restocked)",
    "Netherite Chest Upgrade (Itemsanity) (Iron Chests: Restocked)",
    "Iron Chest Upgrade (Itemsanity) (Iron Chests: Restocked)",
    "Crystal Chest Upgrade (Itemsanity) (Iron Chests: Restocked)",
    "Gold Chest Upgrade (Itemsanity) (Iron Chests: Restocked)"
]