create_itemsanity = [
    "Schematicannon (Itemsanity) (Create)",
    "Schematic Table (Itemsanity) (Create)",
    "Shaft (Itemsanity) (Create)",
    "Cogwheel (Itemsanity) (Create)",
    "Large Cogwheel (Itemsanity) (Create)",
    # "Andesite Encased Shaft (Itemsanity) (Create)",
    # "Brass Encased Shaft (Itemsanity) (Create)",
    # "Andesite Encased Cogwheel (Itemsanity) (Create)",
    # "Brass Encased Cogwheel (Itemsanity) (Create)",
    # "Andesite Encased Large Cogwheel (Itemsanity) (Create)",
    # "Brass Encased Large Cogwheel (Itemsanity) (Create)",
    "Gearbox (Itemsanity) (Create)",
    "Clutch (Itemsanity) (Create)",
    "Gearshift (Itemsanity) (Create)",
    "Encased Chain Drive (Itemsanity) (Create)",
    "Adjustable Chain Gearshift (Itemsanity) (Create)",
    "Chain Conveyor (Itemsanity) (Create)",
    # "Creative Motor (Itemsanity) (Create)",
    "Water Wheel (Itemsanity) (Create)",
    "Large Water Wheel (Itemsanity) (Create)",
    "Encased Fan (Itemsanity) (Create)",
    "Nozzle (Itemsanity) (Create)",
    "Turntable (Itemsanity) (Create)",
    "Hand Crank (Itemsanity) (Create)",
    "Cuckoo Clock (Itemsanity) (Create)",
    "Millstone (Itemsanity) (Create)",
    "Crushing Wheel (Itemsanity) (Create)",
    "Mechanical Press (Itemsanity) (Create)",
    "Mechanical Mixer (Itemsanity) (Create)",
    "Basin (Itemsanity) (Create)",
    "Blaze Burner (Itemsanity) (Create)",
    "Depot (Itemsanity) (Create)",
    "Weighted Ejector (Itemsanity) (Create)",
    "Chute (Itemsanity) (Create)",
    "Smart Chute (Itemsanity) (Create)",
    "Speedometer (Itemsanity) (Create)",
    "Stressometer (Itemsanity) (Create)",
    "Wooden Bracket (Itemsanity) (Create)",
    "Metal Bracket (Itemsanity) (Create)",
    "Fluid Pipe (Itemsanity) (Create)",
    "Mechanical Pump (Itemsanity) (Create)",
    "Smart Fluid Pipe (Itemsanity) (Create)",
    "Fluid Valve (Itemsanity) (Create)",
    "Copper Valve Handle (Itemsanity) (Create)",
    "White Valve Handle (Itemsanity) (Create)",
    "Orange Valve Handle (Itemsanity) (Create)",
    "Magenta Valve Handle (Itemsanity) (Create)",
    "Light Blue Valve Handle (Itemsanity) (Create)",
    "Yellow Valve Handle (Itemsanity) (Create)",
    "Lime Valve Handle (Itemsanity) (Create)",
    "Pink Valve Handle (Itemsanity) (Create)",
    "Gray Valve Handle (Itemsanity) (Create)",
    "Light Gray Valve Handle (Itemsanity) (Create)",
    "Cyan Valve Handle (Itemsanity) (Create)",
    "Purple Valve Handle (Itemsanity) (Create)",
    "Blue Valve Handle (Itemsanity) (Create)",
    "Brown Valve Handle (Itemsanity) (Create)",
    "Green Valve Handle (Itemsanity) (Create)",
    "Red Valve Handle (Itemsanity) (Create)",
    "Black Valve Handle (Itemsanity) (Create)",
    "Fluid Tank (Itemsanity) (Create)",
    # "Creative Fluid Tank (Itemsanity) (Create)",
    "Hose Pulley (Itemsanity) (Create)",
    "Item Drain (Itemsanity) (Create)",
    "Spout (Itemsanity) (Create)",
    "Portable Fluid Interface (Itemsanity) (Create)",
    "Steam Engine (Itemsanity) (Create)",
    "Steam Whistle (Itemsanity) (Create)",
    "Mechanical Piston (Itemsanity) (Create)",
    "Sticky Mechanical Piston (Itemsanity) (Create)",
    "Piston Extension Pole (Itemsanity) (Create)",
    "Gantry Carriage (Itemsanity) (Create)",
    "Gantry Shaft (Itemsanity) (Create)",
    "Windmill Bearing (Itemsanity) (Create)",
    "Mechanical Bearing (Itemsanity) (Create)",
    "Clockwork Bearing (Itemsanity) (Create)",
    "Rope Pulley (Itemsanity) (Create)",
    "Elevator Pulley (Itemsanity) (Create)",
    "Cart Assembler (Itemsanity) (Create)",
    "Controller Rail (Itemsanity) (Create)",
    "Linear Chassis (Itemsanity) (Create)",
    "Secondary Linear Chassis (Itemsanity) (Create)",
    "Radial Chassis (Itemsanity) (Create)",
    "Sticker (Itemsanity) (Create)",
    "Contraption Controls (Itemsanity) (Create)",
    "Mechanical Drill (Itemsanity) (Create)",
    "Mechanical Saw (Itemsanity) (Create)",
    "Deployer (Itemsanity) (Create)",
    "Portable Storage Interface (Itemsanity) (Create)",
    "Redstone Contact (Itemsanity) (Create)",
    # "Elevator Contact (Itemsanity) (Create)",
    "Mechanical Harvester (Itemsanity) (Create)",
    "Mechanical Plough (Itemsanity) (Create)",
    "Mechanical Roller (Itemsanity) (Create)",
    "Windmill Sail Frame (Itemsanity) (Create)",
    "Windmill Sail (Itemsanity) (Create)",
    "Andesite Casing (Itemsanity) (Create)",
    "Brass Casing (Itemsanity) (Create)",
    "Copper Casing (Itemsanity) (Create)",
    # "Shadow Casing (Itemsanity) (Create)",
    # "Radiant Casing (Itemsanity) (Create)",
    "Mechanical Crafter (Itemsanity) (Create)",
    "Sequenced Gearshift (Itemsanity) (Create)",
    "Flywheel (Itemsanity) (Create)",
    "Rotation Speed Controller (Itemsanity) (Create)",
    "Mechanical Arm (Itemsanity) (Create)",
    "Train Track (Itemsanity) (Create)",
    "Train Casing (Itemsanity) (Create)",
    "Train Station (Itemsanity) (Create)",
    "Train Signal (Itemsanity) (Create)",
    "Train Observer (Itemsanity) (Create)",
    "Train Controls (Itemsanity) (Create)",
    "Andesite Funnel (Itemsanity) (Create)",
    "Brass Funnel (Itemsanity) (Create)",
    "Andesite Tunnel (Itemsanity) (Create)",
    "Brass Tunnel (Itemsanity) (Create)",
    "Smart Observer (Itemsanity) (Create)",
    "Threshold Switch (Itemsanity) (Create)",
    # "Creative Crate (Itemsanity) (Create)",
    "Item Vault (Itemsanity) (Create)",
    "Item Hatch (Itemsanity) (Create)",
    "Packager (Itemsanity) (Create)",
    "Re-Packager (Itemsanity) (Create)",
    "Package Frogport (Itemsanity) (Create)",
    "White Postbox (Itemsanity) (Create)",
    "Orange Postbox (Itemsanity) (Create)",
    "Magenta Postbox (Itemsanity) (Create)",
    "Light Blue Postbox (Itemsanity) (Create)",
    "Yellow Postbox (Itemsanity) (Create)",
    "Lime Postbox (Itemsanity) (Create)",
    "Pink Postbox (Itemsanity) (Create)",
    "Gray Postbox (Itemsanity) (Create)",
    "Light Gray Postbox (Itemsanity) (Create)",
    "Cyan Postbox (Itemsanity) (Create)",
    "Purple Postbox (Itemsanity) (Create)",
    "Blue Postbox (Itemsanity) (Create)",
    "Brown Postbox (Itemsanity) (Create)",
    "Green Postbox (Itemsanity) (Create)",
    "Red Postbox (Itemsanity) (Create)",
    "Black Postbox (Itemsanity) (Create)",
    "Stock Link (Itemsanity) (Create)",
    "Stock Ticker (Itemsanity) (Create)",
    "Redstone Requester (Itemsanity) (Create)",
    "Factory Gauge (Itemsanity) (Create)",
    "White Table Cloth (Itemsanity) (Create)",
    "Orange Table Cloth (Itemsanity) (Create)",
    "Magenta Table Cloth (Itemsanity) (Create)",
    "Light Blue Table Cloth (Itemsanity) (Create)",
    "Yellow Table Cloth (Itemsanity) (Create)",
    "Lime Table Cloth (Itemsanity) (Create)",
    "Pink Table Cloth (Itemsanity) (Create)",
    "Gray Table Cloth (Itemsanity) (Create)",
    "Light Gray Table Cloth (Itemsanity) (Create)",
    "Cyan Table Cloth (Itemsanity) (Create)",
    "Purple Table Cloth (Itemsanity) (Create)",
    "Blue Table Cloth (Itemsanity) (Create)",
    "Brown Table Cloth (Itemsanity) (Create)",
    "Green Table Cloth (Itemsanity) (Create)",
    "Red Table Cloth (Itemsanity) (Create)",
    "Black Table Cloth (Itemsanity) (Create)",
    "Andesite Table Cover (Itemsanity) (Create)",
    "Brass Table Cover (Itemsanity) (Create)",
    "Copper Table Cover (Itemsanity) (Create)",
    "Display Link (Itemsanity) (Create)",
    "Display Board (Itemsanity) (Create)",
    "Nixie Tube (Itemsanity) (Create)",
    "Rose Quartz Lamp (Itemsanity) (Create)",
    "Redstone Link (Itemsanity) (Create)",
    "Analog Lever (Itemsanity) (Create)",
    "Placard (Itemsanity) (Create)",
    "Pulse Repeater (Itemsanity) (Create)",
    "Pulse Extender (Itemsanity) (Create)",
    "Pulse Timer (Itemsanity) (Create)",
    "Powered Latch (Itemsanity) (Create)",
    "Powered Toggle Latch (Itemsanity) (Create)",
    "Wheat Flour (Itemsanity) (Create)",
    "Dough (Itemsanity) (Create)",
    "Cinder Flour (Itemsanity) (Create)",
    "Rose Quartz (Itemsanity) (Create)",
    "Polished Rose Quartz (Itemsanity) (Create)",
    "Powdered Obsidian (Itemsanity) (Create)",
    "Sturdy Sheet (Itemsanity) (Create)",
    "Propeller (Itemsanity) (Create)",
    "Whisk (Itemsanity) (Create)",
    "Brass Hand (Itemsanity) (Create)",
    "Crafter Slot Cover (Itemsanity) (Create)",
    "Electron Tube (Itemsanity) (Create)",
    "Transmitter (Itemsanity) (Create)",
    "Pulp (Itemsanity) (Create)",
    "Cardboard (Itemsanity) (Create)",
    "Incomplete Precision Mechanism (Itemsanity) (Create)",
    "Unprocessed Obsidian Sheet (Itemsanity) (Create)",
    "Incomplete Track (Itemsanity) (Create)",
    "Precision Mechanism (Itemsanity) (Create)",
    "Blaze Cake Base (Itemsanity) (Create)",
    "Blaze Cake (Itemsanity) (Create)",
    # "Creative Blaze Cake (Itemsanity) (Create)",
    "Bar of Chocolate (Itemsanity) (Create)",
    "Sweet Roll (Itemsanity) (Create)",
    "Chocolate Glazed Berries (Itemsanity) (Create)",
    "Honeyed Apple (Itemsanity) (Create)",
    "Builder's Tea (Itemsanity) (Create)",
    "Cardboard Sword (Itemsanity) (Create)",
    "Raw Zinc (Itemsanity) (Create)",
    "Andesite Alloy (Itemsanity) (Create)",
    "Zinc Ingot (Itemsanity) (Create)",
    "Brass Ingot (Itemsanity) (Create)",
    # "Chromatic Compound (Itemsanity) (Create)",
    # "Shadow Steel (Itemsanity) (Create)",
    # "Refined Radiance (Itemsanity) (Create)",
    "Copper Nugget (Itemsanity) (Create)",
    "Zinc Nugget (Itemsanity) (Create)",
    "Brass Nugget (Itemsanity) (Create)",
    "Nugget of Experience (Itemsanity) (Create)",
    "Copper Sheet (Itemsanity) (Create)",
    "Brass Sheet (Itemsanity) (Create)",
    "Iron Sheet (Itemsanity) (Create)",
    "Golden Sheet (Itemsanity) (Create)",
    "Crushed Raw Iron (Itemsanity) (Create)",
    "Crushed Raw Gold (Itemsanity) (Create)",
    "Crushed Raw Copper (Itemsanity) (Create)",
    "Crushed Raw Zinc (Itemsanity) (Create)",
    # "Crushed Raw Osmium (Itemsanity) (Create)",
    # "Crushed Raw Platinum (Itemsanity) (Create)",
    # "Crushed Raw Silver (Itemsanity) (Create)",
    # "Crushed Raw Tin (Itemsanity) (Create)",
    # "Crushed Raw Lead (Itemsanity) (Create)",
    # "Crushed Raw Quicksilver (Itemsanity) (Create)",
    # "Crushed Raw Aluminum (Itemsanity) (Create)",
    # "Crushed Raw Uranium (Itemsanity) (Create)",
    # "Crushed Raw Nickel (Itemsanity) (Create)",
    "Mechanical Belt (Itemsanity) (Create)",
    "Vertical Gearbox (Itemsanity) (Create)",
    "Empty Blaze Burner (Itemsanity) (Create)",
    "Engineer's Goggles (Itemsanity) (Create)",
    "Super Glue (Itemsanity) (Create)",
    "Minecart Coupling (Itemsanity) (Create)",
    "Crafting Blueprint (Itemsanity) (Create)",
    # "Copper Backtank Placeable (Itemsanity) (Create)",
    # "Netherite Backtank Placeable (Itemsanity) (Create)",
    "Copper Backtank (Itemsanity) (Create)",
    "Netherite Backtank (Itemsanity) (Create)",
    "Copper Diving Helmet (Itemsanity) (Create)",
    "Netherite Diving Helmet (Itemsanity) (Create)",
    "Copper Diving Boots (Itemsanity) (Create)",
    "Netherite Diving Boots (Itemsanity) (Create)",
    "Cardboard Helmet (Itemsanity) (Create)",
    "Cardboard Chestplate (Itemsanity) (Create)",
    "Cardboard Leggings (Itemsanity) (Create)",
    "Cardboard Boots (Itemsanity) (Create)",
    "Sand Paper (Itemsanity) (Create)",
    "Red Sand Paper (Itemsanity) (Create)",
    "Wrench (Itemsanity) (Create)",
    # "Minecart Contraption (Itemsanity) (Create)",
    # "Furnace Minecart Contraption (Itemsanity) (Create)",
    # "Chest Minecart Contraption (Itemsanity) (Create)",
    "Linked Controller (Itemsanity) (Create)",
    "Potato Cannon (Itemsanity) (Create)",
    "Extendo Grip (Itemsanity) (Create)",
    "Wand Of Symmetry (Itemsanity) (Create)",
    # "Creative Worldshaper (Itemsanity) (Create)",
    "Tree Fertilizer (Itemsanity) (Create)",
    # "Cardboard Package (Itemsanity) (Create)",
    # "Cardboard Package (Itemsanity) (Create)",
    # "Cardboard Package (Itemsanity) (Create)",
    # "Cardboard Package (Itemsanity) (Create)",
    # "Rare Package (Itemsanity) (Create)",
    # "Rare Package (Itemsanity) (Create)",
    # "Rare Package (Itemsanity) (Create)",
    # "Rare Package (Itemsanity) (Create)",
    # "Rare Package (Itemsanity) (Create)",
    # "Rare Package (Itemsanity) (Create)",
    # "Rare Package (Itemsanity) (Create)",
    # "Rare Package (Itemsanity) (Create)",
    # "Rare Package (Itemsanity) (Create)",
    # "Rare Package (Itemsanity) (Create)",
    "List Filter (Itemsanity) (Create)",
    "Attribute Filter (Itemsanity) (Create)",
    "Package Filter (Itemsanity) (Create)",
    "Train Schedule (Itemsanity) (Create)",
    # "Shopping List (Itemsanity) (Create)",
    "Empty Schematic (Itemsanity) (Create)",
    "Schematic And Quill (Itemsanity) (Create)",
    # "Schematic (Itemsanity) (Create)",
    "Peculiar Bell (Itemsanity) (Create)",
    "Haunted Bell (Itemsanity) (Create)",
    "Desk Bell (Itemsanity) (Create)",
    "White Toolbox (Itemsanity) (Create)",
    "Orange Toolbox (Itemsanity) (Create)",
    "Magenta Toolbox (Itemsanity) (Create)",
    "Light Blue Toolbox (Itemsanity) (Create)",
    "Yellow Toolbox (Itemsanity) (Create)",
    "Lime Toolbox (Itemsanity) (Create)",
    "Pink Toolbox (Itemsanity) (Create)",
    "Gray Toolbox (Itemsanity) (Create)",
    "Light Gray Toolbox (Itemsanity) (Create)",
    "Cyan Toolbox (Itemsanity) (Create)",
    "Purple Toolbox (Itemsanity) (Create)",
    "Blue Toolbox (Itemsanity) (Create)",
    "Brown Toolbox (Itemsanity) (Create)",
    "Green Toolbox (Itemsanity) (Create)",
    "Red Toolbox (Itemsanity) (Create)",
    "Black Toolbox (Itemsanity) (Create)",
    "Clipboard (Itemsanity) (Create)",
    "Andesite Ladder (Itemsanity) (Create)",
    "Brass Ladder (Itemsanity) (Create)",
    "Copper Ladder (Itemsanity) (Create)",
    "Andesite Bars (Itemsanity) (Create)",
    "Brass Bars (Itemsanity) (Create)",
    "Copper Bars (Itemsanity) (Create)",
    "Andesite Scaffolding (Itemsanity) (Create)",
    "Brass Scaffolding (Itemsanity) (Create)",
    "Copper Scaffolding (Itemsanity) (Create)",
    "Metal Girder (Itemsanity) (Create)",
    "Copycat Step (Itemsanity) (Create)",
    "Copycat Panel (Itemsanity) (Create)",
    "White Seat (Itemsanity) (Create)",
    "Orange Seat (Itemsanity) (Create)",
    "Magenta Seat (Itemsanity) (Create)",
    "Light Blue Seat (Itemsanity) (Create)",
    "Yellow Seat (Itemsanity) (Create)",
    "Lime Seat (Itemsanity) (Create)",
    "Pink Seat (Itemsanity) (Create)",
    "Gray Seat (Itemsanity) (Create)",
    "Light Gray Seat (Itemsanity) (Create)",
    "Cyan Seat (Itemsanity) (Create)",
    "Purple Seat (Itemsanity) (Create)",
    "Blue Seat (Itemsanity) (Create)",
    "Brown Seat (Itemsanity) (Create)",
    "Green Seat (Itemsanity) (Create)",
    "Red Seat (Itemsanity) (Create)",
    "Black Seat (Itemsanity) (Create)",
    "Andesite Door (Itemsanity) (Create)",
    "Brass Door (Itemsanity) (Create)",
    "Copper Door (Itemsanity) (Create)",
    "Train Door (Itemsanity) (Create)",
    "Train Trapdoor (Itemsanity) (Create)",
    "Framed Glass Door (Itemsanity) (Create)",
    "Framed Glass Trapdoor (Itemsanity) (Create)",
    "Zinc Ore (Itemsanity) (Create)",
    "Deepslate Zinc Ore (Itemsanity) (Create)",
    "Block of Raw Zinc (Itemsanity) (Create)",
    "Block of Zinc (Itemsanity) (Create)",
    "Block of Andesite Alloy (Itemsanity) (Create)",
    "Block of Industrial Iron (Itemsanity) (Create)",
    "Block of Weathered Iron (Itemsanity) (Create)",
    "Block of Brass (Itemsanity) (Create)",
    "Block of Cardboard (Itemsanity) (Create)",
    "Bound Block of Cardboard (Itemsanity) (Create)",
    "Block of Experience (Itemsanity) (Create)",
    "Block of Rose Quartz (Itemsanity) (Create)",
    "Rose Quartz Tiles (Itemsanity) (Create)",
    "Small Rose Quartz Tiles (Itemsanity) (Create)",
    "Copper Shingles (Itemsanity) (Create)",
    "Exposed Copper Shingles (Itemsanity) (Create)",
    "Weathered Copper Shingles (Itemsanity) (Create)",
    "Oxidized Copper Shingles (Itemsanity) (Create)",
    "Copper Shingle Slab (Itemsanity) (Create)",
    "Exposed Copper Shingle Slab (Itemsanity) (Create)",
    "Weathered Copper Shingle Slab (Itemsanity) (Create)",
    "Oxidized Copper Shingle Slab (Itemsanity) (Create)",
    "Copper Shingle Stairs (Itemsanity) (Create)",
    "Exposed Copper Shingle Stairs (Itemsanity) (Create)",
    "Weathered Copper Shingle Stairs (Itemsanity) (Create)",
    "Oxidized Copper Shingle Stairs (Itemsanity) (Create)",
    "Waxed Copper Shingles (Itemsanity) (Create)",
    "Waxed Exposed Copper Shingles (Itemsanity) (Create)",
    "Waxed Weathered Copper Shingles (Itemsanity) (Create)",
    "Waxed Oxidized Copper Shingles (Itemsanity) (Create)",
    "Waxed Copper Shingle Slab (Itemsanity) (Create)",
    "Waxed Exposed Copper Shingle Slab (Itemsanity) (Create)",
    "Waxed Weathered Copper Shingle Slab (Itemsanity) (Create)",
    "Waxed Oxidized Copper Shingle Slab (Itemsanity) (Create)",
    "Waxed Copper Shingle Stairs (Itemsanity) (Create)",
    "Waxed Exposed Copper Shingle Stairs (Itemsanity) (Create)",
    "Waxed Weathered Copper Shingle Stairs (Itemsanity) (Create)",
    "Waxed Oxidized Copper Shingle Stairs (Itemsanity) (Create)",
    "Copper Tiles (Itemsanity) (Create)",
    "Exposed Copper Tiles (Itemsanity) (Create)",
    "Weathered Copper Tiles (Itemsanity) (Create)",
    "Oxidized Copper Tiles (Itemsanity) (Create)",
    "Copper Tile Slab (Itemsanity) (Create)",
    "Exposed Copper Tile Slab (Itemsanity) (Create)",
    "Weathered Copper Tile Slab (Itemsanity) (Create)",
    "Oxidized Copper Tile Slab (Itemsanity) (Create)",
    "Copper Tile Stairs (Itemsanity) (Create)",
    "Exposed Copper Tile Stairs (Itemsanity) (Create)",
    "Weathered Copper Tile Stairs (Itemsanity) (Create)",
    "Oxidized Copper Tile Stairs (Itemsanity) (Create)",
    "Waxed Copper Tiles (Itemsanity) (Create)",
    "Waxed Exposed Copper Tiles (Itemsanity) (Create)",
    "Waxed Weathered Copper Tiles (Itemsanity) (Create)",
    "Waxed Oxidized Copper Tiles (Itemsanity) (Create)",
    "Waxed Copper Tile Slab (Itemsanity) (Create)",
    "Waxed Exposed Copper Tile Slab (Itemsanity) (Create)",
    "Waxed Weathered Copper Tile Slab (Itemsanity) (Create)",
    "Waxed Oxidized Copper Tile Slab (Itemsanity) (Create)",
    "Waxed Copper Tile Stairs (Itemsanity) (Create)",
    "Waxed Exposed Copper Tile Stairs (Itemsanity) (Create)",
    "Waxed Weathered Copper Tile Stairs (Itemsanity) (Create)",
    "Waxed Oxidized Copper Tile Stairs (Itemsanity) (Create)",
    "Honey Bucket (Itemsanity) (Create)",
    "Chocolate Bucket (Itemsanity) (Create)",
    "Tiled Glass (Itemsanity) (Create)",
    "Framed Glass (Itemsanity) (Create)",
    "Horizontal Framed Glass (Itemsanity) (Create)",
    "Vertical Framed Glass (Itemsanity) (Create)",
    "Tiled Glass Pane (Itemsanity) (Create)",
    "Framed Glass Pane (Itemsanity) (Create)",
    "Horizontal Framed Glass Pane (Itemsanity) (Create)",
    "Vertical Framed Glass Pane (Itemsanity) (Create)",
    "Oak Window (Itemsanity) (Create)",
    "Spruce Window (Itemsanity) (Create)",
    "Birch Window (Itemsanity) (Create)",
    "Jungle Window (Itemsanity) (Create)",
    "Acacia Window (Itemsanity) (Create)",
    "Dark Oak Window (Itemsanity) (Create)",
    "Mangrove Window (Itemsanity) (Create)",
    "Crimson Window (Itemsanity) (Create)",
    "Warped Window (Itemsanity) (Create)",
    "Cherry Window (Itemsanity) (Create)",
    "Bamboo Window (Itemsanity) (Create)",
    "Ornate Iron Window (Itemsanity) (Create)",
    "Industrial Iron Window (Itemsanity) (Create)",
    "Weathered Iron Window (Itemsanity) (Create)",
    "Oak Window Pane (Itemsanity) (Create)",
    "Spruce Window Pane (Itemsanity) (Create)",
    "Birch Window Pane (Itemsanity) (Create)",
    "Jungle Window Pane (Itemsanity) (Create)",
    "Acacia Window Pane (Itemsanity) (Create)",
    "Dark Oak Window Pane (Itemsanity) (Create)",
    "Mangrove Window Pane (Itemsanity) (Create)",
    "Crimson Window Pane (Itemsanity) (Create)",
    "Warped Window Pane (Itemsanity) (Create)",
    "Cherry Window Pane (Itemsanity) (Create)",
    "Bamboo Window Pane (Itemsanity) (Create)",
    "Ornate Iron Window Pane (Itemsanity) (Create)",
    "Industrial Iron Window Pane (Itemsanity) (Create)",
    "Weathered Iron Window Pane (Itemsanity) (Create)",
    "Cut Granite (Itemsanity) (Create)",
    "Cut Granite Stairs (Itemsanity) (Create)",
    "Cut Granite Slab (Itemsanity) (Create)",
    "Cut Granite Wall (Itemsanity) (Create)",
    "Polished Cut Granite (Itemsanity) (Create)",
    "Polished Cut Granite Stairs (Itemsanity) (Create)",
    "Polished Cut Granite Slab (Itemsanity) (Create)",
    "Polished Cut Granite Wall (Itemsanity) (Create)",
    "Cut Granite Bricks (Itemsanity) (Create)",
    "Cut Granite Brick Stairs (Itemsanity) (Create)",
    "Cut Granite Brick Slab (Itemsanity) (Create)",
    "Cut Granite Brick Wall (Itemsanity) (Create)",
    "Small Granite Bricks (Itemsanity) (Create)",
    "Small Granite Brick Stairs (Itemsanity) (Create)",
    "Small Granite Brick Slab (Itemsanity) (Create)",
    "Small Granite Brick Wall (Itemsanity) (Create)",
    "Layered Granite (Itemsanity) (Create)",
    "Granite Pillar (Itemsanity) (Create)",
    "Cut Diorite (Itemsanity) (Create)",
    "Cut Diorite Stairs (Itemsanity) (Create)",
    "Cut Diorite Slab (Itemsanity) (Create)",
    "Cut Diorite Wall (Itemsanity) (Create)",
    "Polished Cut Diorite (Itemsanity) (Create)",
    "Polished Cut Diorite Stairs (Itemsanity) (Create)",
    "Polished Cut Diorite Slab (Itemsanity) (Create)",
    "Polished Cut Diorite Wall (Itemsanity) (Create)",
    "Cut Diorite Bricks (Itemsanity) (Create)",
    "Cut Diorite Brick Stairs (Itemsanity) (Create)",
    "Cut Diorite Brick Slab (Itemsanity) (Create)",
    "Cut Diorite Brick Wall (Itemsanity) (Create)",
    "Small Diorite Bricks (Itemsanity) (Create)",
    "Small Diorite Brick Stairs (Itemsanity) (Create)",
    "Small Diorite Brick Slab (Itemsanity) (Create)",
    "Small Diorite Brick Wall (Itemsanity) (Create)",
    "Layered Diorite (Itemsanity) (Create)",
    "Diorite Pillar (Itemsanity) (Create)",
    "Cut Andesite (Itemsanity) (Create)",
    "Cut Andesite Stairs (Itemsanity) (Create)",
    "Cut Andesite Slab (Itemsanity) (Create)",
    "Cut Andesite Wall (Itemsanity) (Create)",
    "Polished Cut Andesite (Itemsanity) (Create)",
    "Polished Cut Andesite Stairs (Itemsanity) (Create)",
    "Polished Cut Andesite Slab (Itemsanity) (Create)",
    "Polished Cut Andesite Wall (Itemsanity) (Create)",
    "Cut Andesite Bricks (Itemsanity) (Create)",
    "Cut Andesite Brick Stairs (Itemsanity) (Create)",
    "Cut Andesite Brick Slab (Itemsanity) (Create)",
    "Cut Andesite Brick Wall (Itemsanity) (Create)",
    "Small Andesite Bricks (Itemsanity) (Create)",
    "Small Andesite Brick Stairs (Itemsanity) (Create)",
    "Small Andesite Brick Slab (Itemsanity) (Create)",
    "Small Andesite Brick Wall (Itemsanity) (Create)",
    "Layered Andesite (Itemsanity) (Create)",
    "Andesite Pillar (Itemsanity) (Create)",
    "Cut Calcite (Itemsanity) (Create)",
    "Cut Calcite Stairs (Itemsanity) (Create)",
    "Cut Calcite Slab (Itemsanity) (Create)",
    "Cut Calcite Wall (Itemsanity) (Create)",
    "Polished Cut Calcite (Itemsanity) (Create)",
    "Polished Cut Calcite Stairs (Itemsanity) (Create)",
    "Polished Cut Calcite Slab (Itemsanity) (Create)",
    "Polished Cut Calcite Wall (Itemsanity) (Create)",
    "Cut Calcite Bricks (Itemsanity) (Create)",
    "Cut Calcite Brick Stairs (Itemsanity) (Create)",
    "Cut Calcite Brick Slab (Itemsanity) (Create)",
    "Cut Calcite Brick Wall (Itemsanity) (Create)",
    "Small Calcite Bricks (Itemsanity) (Create)",
    "Small Calcite Brick Stairs (Itemsanity) (Create)",
    "Small Calcite Brick Slab (Itemsanity) (Create)",
    "Small Calcite Brick Wall (Itemsanity) (Create)",
    "Layered Calcite (Itemsanity) (Create)",
    "Calcite Pillar (Itemsanity) (Create)",
    "Cut Dripstone (Itemsanity) (Create)",
    "Cut Dripstone Stairs (Itemsanity) (Create)",
    "Cut Dripstone Slab (Itemsanity) (Create)",
    "Cut Dripstone Wall (Itemsanity) (Create)",
    "Polished Cut Dripstone (Itemsanity) (Create)",
    "Polished Cut Dripstone Stairs (Itemsanity) (Create)",
    "Polished Cut Dripstone Slab (Itemsanity) (Create)",
    "Polished Cut Dripstone Wall (Itemsanity) (Create)",
    "Cut Dripstone Bricks (Itemsanity) (Create)",
    "Cut Dripstone Brick Stairs (Itemsanity) (Create)",
    "Cut Dripstone Brick Slab (Itemsanity) (Create)",
    "Cut Dripstone Brick Wall (Itemsanity) (Create)",
    "Small Dripstone Bricks (Itemsanity) (Create)",
    "Small Dripstone Brick Stairs (Itemsanity) (Create)",
    "Small Dripstone Brick Slab (Itemsanity) (Create)",
    "Small Dripstone Brick Wall (Itemsanity) (Create)",
    "Layered Dripstone (Itemsanity) (Create)",
    "Dripstone Pillar (Itemsanity) (Create)",
    "Cut Deepslate (Itemsanity) (Create)",
    "Cut Deepslate Stairs (Itemsanity) (Create)",
    "Cut Deepslate Slab (Itemsanity) (Create)",
    "Cut Deepslate Wall (Itemsanity) (Create)",
    "Polished Cut Deepslate (Itemsanity) (Create)",
    "Polished Cut Deepslate Stairs (Itemsanity) (Create)",
    "Polished Cut Deepslate Slab (Itemsanity) (Create)",
    "Polished Cut Deepslate Wall (Itemsanity) (Create)",
    "Cut Deepslate Bricks (Itemsanity) (Create)",
    "Cut Deepslate Brick Stairs (Itemsanity) (Create)",
    "Cut Deepslate Brick Slab (Itemsanity) (Create)",
    "Cut Deepslate Brick Wall (Itemsanity) (Create)",
    "Small Deepslate Bricks (Itemsanity) (Create)",
    "Small Deepslate Brick Stairs (Itemsanity) (Create)",
    "Small Deepslate Brick Slab (Itemsanity) (Create)",
    "Small Deepslate Brick Wall (Itemsanity) (Create)",
    "Layered Deepslate (Itemsanity) (Create)",
    "Deepslate Pillar (Itemsanity) (Create)",
    "Cut Tuff (Itemsanity) (Create)",
    "Cut Tuff Stairs (Itemsanity) (Create)",
    "Cut Tuff Slab (Itemsanity) (Create)",
    "Cut Tuff Wall (Itemsanity) (Create)",
    "Polished Cut Tuff (Itemsanity) (Create)",
    "Polished Cut Tuff Stairs (Itemsanity) (Create)",
    "Polished Cut Tuff Slab (Itemsanity) (Create)",
    "Polished Cut Tuff Wall (Itemsanity) (Create)",
    "Cut Tuff Bricks (Itemsanity) (Create)",
    "Cut Tuff Brick Stairs (Itemsanity) (Create)",
    "Cut Tuff Brick Slab (Itemsanity) (Create)",
    "Cut Tuff Brick Wall (Itemsanity) (Create)",
    "Small Tuff Bricks (Itemsanity) (Create)",
    "Small Tuff Brick Stairs (Itemsanity) (Create)",
    "Small Tuff Brick Slab (Itemsanity) (Create)",
    "Small Tuff Brick Wall (Itemsanity) (Create)",
    "Layered Tuff (Itemsanity) (Create)",
    "Tuff Pillar (Itemsanity) (Create)",
    "Asurine (Itemsanity) (Create)",
    "Cut Asurine (Itemsanity) (Create)",
    "Cut Asurine Stairs (Itemsanity) (Create)",
    "Cut Asurine Slab (Itemsanity) (Create)",
    "Cut Asurine Wall (Itemsanity) (Create)",
    "Polished Cut Asurine (Itemsanity) (Create)",
    "Polished Cut Asurine Stairs (Itemsanity) (Create)",
    "Polished Cut Asurine Slab (Itemsanity) (Create)",
    "Polished Cut Asurine Wall (Itemsanity) (Create)",
    "Cut Asurine Bricks (Itemsanity) (Create)",
    "Cut Asurine Brick Stairs (Itemsanity) (Create)",
    "Cut Asurine Brick Slab (Itemsanity) (Create)",
    "Cut Asurine Brick Wall (Itemsanity) (Create)",
    "Small Asurine Bricks (Itemsanity) (Create)",
    "Small Asurine Brick Stairs (Itemsanity) (Create)",
    "Small Asurine Brick Slab (Itemsanity) (Create)",
    "Small Asurine Brick Wall (Itemsanity) (Create)",
    "Layered Asurine (Itemsanity) (Create)",
    "Asurine Pillar (Itemsanity) (Create)",
    "Crimsite (Itemsanity) (Create)",
    "Cut Crimsite (Itemsanity) (Create)",
    "Cut Crimsite Stairs (Itemsanity) (Create)",
    "Cut Crimsite Slab (Itemsanity) (Create)",
    "Cut Crimsite Wall (Itemsanity) (Create)",
    "Polished Cut Crimsite (Itemsanity) (Create)",
    "Polished Cut Crimsite Stairs (Itemsanity) (Create)",
    "Polished Cut Crimsite Slab (Itemsanity) (Create)",
    "Polished Cut Crimsite Wall (Itemsanity) (Create)",
    "Cut Crimsite Bricks (Itemsanity) (Create)",
    "Cut Crimsite Brick Stairs (Itemsanity) (Create)",
    "Cut Crimsite Brick Slab (Itemsanity) (Create)",
    "Cut Crimsite Brick Wall (Itemsanity) (Create)",
    "Small Crimsite Bricks (Itemsanity) (Create)",
    "Small Crimsite Brick Stairs (Itemsanity) (Create)",
    "Small Crimsite Brick Slab (Itemsanity) (Create)",
    "Small Crimsite Brick Wall (Itemsanity) (Create)",
    "Layered Crimsite (Itemsanity) (Create)",
    "Crimsite Pillar (Itemsanity) (Create)",
    "Limestone (Itemsanity) (Create)",
    "Cut Limestone (Itemsanity) (Create)",
    "Cut Limestone Stairs (Itemsanity) (Create)",
    "Cut Limestone Slab (Itemsanity) (Create)",
    "Cut Limestone Wall (Itemsanity) (Create)",
    "Polished Cut Limestone (Itemsanity) (Create)",
    "Polished Cut Limestone Stairs (Itemsanity) (Create)",
    "Polished Cut Limestone Slab (Itemsanity) (Create)",
    "Polished Cut Limestone Wall (Itemsanity) (Create)",
    "Cut Limestone Bricks (Itemsanity) (Create)",
    "Cut Limestone Brick Stairs (Itemsanity) (Create)",
    "Cut Limestone Brick Slab (Itemsanity) (Create)",
    "Cut Limestone Brick Wall (Itemsanity) (Create)",
    "Small Limestone Bricks (Itemsanity) (Create)",
    "Small Limestone Brick Stairs (Itemsanity) (Create)",
    "Small Limestone Brick Slab (Itemsanity) (Create)",
    "Small Limestone Brick Wall (Itemsanity) (Create)",
    "Layered Limestone (Itemsanity) (Create)",
    "Limestone Pillar (Itemsanity) (Create)",
    "Ochrum (Itemsanity) (Create)",
    "Cut Ochrum (Itemsanity) (Create)",
    "Cut Ochrum Stairs (Itemsanity) (Create)",
    "Cut Ochrum Slab (Itemsanity) (Create)",
    "Cut Ochrum Wall (Itemsanity) (Create)",
    "Polished Cut Ochrum (Itemsanity) (Create)",
    "Polished Cut Ochrum Stairs (Itemsanity) (Create)",
    "Polished Cut Ochrum Slab (Itemsanity) (Create)",
    "Polished Cut Ochrum Wall (Itemsanity) (Create)",
    "Cut Ochrum Bricks (Itemsanity) (Create)",
    "Cut Ochrum Brick Stairs (Itemsanity) (Create)",
    "Cut Ochrum Brick Slab (Itemsanity) (Create)",
    "Cut Ochrum Brick Wall (Itemsanity) (Create)",
    "Small Ochrum Bricks (Itemsanity) (Create)",
    "Small Ochrum Brick Stairs (Itemsanity) (Create)",
    "Small Ochrum Brick Slab (Itemsanity) (Create)",
    "Small Ochrum Brick Wall (Itemsanity) (Create)",
    "Layered Ochrum (Itemsanity) (Create)",
    "Ochrum Pillar (Itemsanity) (Create)",
    "Scoria (Itemsanity) (Create)",
    "Cut Scoria (Itemsanity) (Create)",
    "Cut Scoria Stairs (Itemsanity) (Create)",
    "Cut Scoria Slab (Itemsanity) (Create)",
    "Cut Scoria Wall (Itemsanity) (Create)",
    "Polished Cut Scoria (Itemsanity) (Create)",
    "Polished Cut Scoria Stairs (Itemsanity) (Create)",
    "Polished Cut Scoria Slab (Itemsanity) (Create)",
    "Polished Cut Scoria Wall (Itemsanity) (Create)",
    "Cut Scoria Bricks (Itemsanity) (Create)",
    "Cut Scoria Brick Stairs (Itemsanity) (Create)",
    "Cut Scoria Brick Slab (Itemsanity) (Create)",
    "Cut Scoria Brick Wall (Itemsanity) (Create)",
    "Small Scoria Bricks (Itemsanity) (Create)",
    "Small Scoria Brick Stairs (Itemsanity) (Create)",
    "Small Scoria Brick Slab (Itemsanity) (Create)",
    "Small Scoria Brick Wall (Itemsanity) (Create)",
    "Layered Scoria (Itemsanity) (Create)",
    "Scoria Pillar (Itemsanity) (Create)",
    "Scorchia (Itemsanity) (Create)",
    "Cut Scorchia (Itemsanity) (Create)",
    "Cut Scorchia Stairs (Itemsanity) (Create)",
    "Cut Scorchia Slab (Itemsanity) (Create)",
    "Cut Scorchia Wall (Itemsanity) (Create)",
    "Polished Cut Scorchia (Itemsanity) (Create)",
    "Polished Cut Scorchia Stairs (Itemsanity) (Create)",
    "Polished Cut Scorchia Slab (Itemsanity) (Create)",
    "Polished Cut Scorchia Wall (Itemsanity) (Create)",
    "Cut Scorchia Bricks (Itemsanity) (Create)",
    "Cut Scorchia Brick Stairs (Itemsanity) (Create)",
    "Cut Scorchia Brick Slab (Itemsanity) (Create)",
    "Cut Scorchia Brick Wall (Itemsanity) (Create)",
    "Small Scorchia Bricks (Itemsanity) (Create)",
    "Small Scorchia Brick Stairs (Itemsanity) (Create)",
    "Small Scorchia Brick Slab (Itemsanity) (Create)",
    "Small Scorchia Brick Wall (Itemsanity) (Create)",
    "Layered Scorchia (Itemsanity) (Create)",
    "Scorchia Pillar (Itemsanity) (Create)",
    "Veridium (Itemsanity) (Create)",
    "Cut Veridium (Itemsanity) (Create)",
    "Cut Veridium Stairs (Itemsanity) (Create)",
    "Cut Veridium Slab (Itemsanity) (Create)",
    "Cut Veridium Wall (Itemsanity) (Create)",
    "Polished Cut Veridium (Itemsanity) (Create)",
    "Polished Cut Veridium Stairs (Itemsanity) (Create)",
    "Polished Cut Veridium Slab (Itemsanity) (Create)",
    "Polished Cut Veridium Wall (Itemsanity) (Create)",
    "Cut Veridium Bricks (Itemsanity) (Create)",
    "Cut Veridium Brick Stairs (Itemsanity) (Create)",
    "Cut Veridium Brick Slab (Itemsanity) (Create)",
    "Cut Veridium Brick Wall (Itemsanity) (Create)",
    "Small Veridium Bricks (Itemsanity) (Create)",
    "Small Veridium Brick Stairs (Itemsanity) (Create)",
    "Small Veridium Brick Slab (Itemsanity) (Create)",
    "Small Veridium Brick Wall (Itemsanity) (Create)",
    "Layered Veridium (Itemsanity) (Create)",
    "Veridium Pillar (Itemsanity) (Create)",
]