healpgood_itemsanity = [
    "Heart Crystal Sliver (Itemsanity) (Healing Pretty Good)",
    "Heart Crystal Shard (Itemsanity) (Healing Pretty Good)",
    "Heart Piece (Itemsanity) (Healing Pretty Good)",
    "Bottle O' Healing (Itemsanity) (Healing Pretty Good)",
    "Heart Cookie (Itemsanity) (Healing Pretty Good)",
    "Crystal Apple (Itemsanity) (Healing Pretty Good)",
    "Crystal Heart (Itemsanity) (Healing Pretty Good)",
    "Heart Container (Itemsanity) (Healing Pretty Good)",
    "Empty Heart Container (Itemsanity) (Healing Pretty Good)",
    "Music Disc Heartstep (Itemsanity) (Healing Pretty Good)",
    "Heart Crystal Block (Itemsanity) (Healing Pretty Good)",
    "Polished Heart Crystal (Itemsanity) (Healing Pretty Good)",
    "Polished Heart Crystal Stairs (Itemsanity) (Healing Pretty Good)",
    "Polished Heart Crystal Slab (Itemsanity) (Healing Pretty Good)",
    "Heart Crystal Bricks (Itemsanity) (Healing Pretty Good)",
    "Heart Crystal Brick Stairs (Itemsanity) (Healing Pretty Good)",
    "Heart Crystal Brick Slab (Itemsanity) (Healing Pretty Good)",
    "Heart Lantern (Itemsanity) (Healing Pretty Good)"
]